[project]
name = "rootcause-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arize-otel>=0.11.0",
    "google-adk>=1.19.0",
    "openinference-instrumentation-google-adk>=0.1.6",
    "pytest>=9.0.1",
    "ruff>=0.14.6",
]
